server {
    listen 80;
    listen [::]:80;
    server_name azoralang.org www.azoralang.org;

    root /var/www/azoralang.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name docs.azoralang.org;

    root /var/www/docs.azoralang.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name code.azoralang.org;

    root /var/www/code.azoralang.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name book.azoralang.org;

    root /var/www/book.azoralang.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
