server {
    listen 80;
    listen [::]:80;
    server_name azoralabs.org www.azoralabs.org;

    root /var/www/azoralabs.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name azoraengine.org www.azoraengine.org;

    root /var/www/azoraengine.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name azorastudio.org www.azorastudio.org;

    root /var/www/azorastudio.org/html;
    index index.html;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
